#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';

const columns = 112;
const rows = 50;
const sampleStepDegrees = 0.9;
const latitudeExtent = {
  min: -60,
  max: 85,
};
const landUrl =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson';
const outPath = path.join(process.cwd(), 'src/data/worldPixelAtlas.ts');

const equalEarth = {
  a1: 1.340264,
  a2: -0.081106,
  a3: 0.000893,
  a4: 0.003796,
};

function projectEqualEarth(lon, lat) {
  const lambda = (lon * Math.PI) / 180;
  const phi = (lat * Math.PI) / 180;
  const theta = Math.asin((Math.sqrt(3) / 2) * Math.sin(phi));
  const theta2 = theta * theta;
  const theta6 = theta2 * theta2 * theta2;
  const denominator =
    3 *
    (9 * equalEarth.a4 * theta6 * theta2 +
      7 * equalEarth.a3 * theta6 +
      3 * equalEarth.a2 * theta2 +
      equalEarth.a1);
  const x = (2 * Math.sqrt(3) * lambda * Math.cos(theta)) / denominator;
  const y =
    equalEarth.a4 * theta6 * theta2 * theta +
    equalEarth.a3 * theta6 * theta +
    equalEarth.a2 * theta2 * theta +
    equalEarth.a1 * theta;
  return [x, y];
}

function computeBounds() {
  const points = [];
  for (let lat = latitudeExtent.min; lat <= latitudeExtent.max; lat += 0.25) {
    points.push(projectEqualEarth(-180, lat), projectEqualEarth(180, lat));
  }
  for (let lon = -180; lon <= 180; lon += 0.25) {
    points.push(projectEqualEarth(lon, latitudeExtent.min), projectEqualEarth(lon, latitudeExtent.max));
  }
  return {
    minX: Math.min(...points.map(([x]) => x)),
    maxX: Math.max(...points.map(([x]) => x)),
    minY: Math.min(...points.map(([, y]) => y)),
    maxY: Math.max(...points.map(([, y]) => y)),
  };
}

function coordinateToCell(lon, lat, bounds) {
  const [x, y] = projectEqualEarth(lon, lat);
  const column = Math.max(1, Math.min(columns, Math.floor(((x - bounds.minX) / (bounds.maxX - bounds.minX)) * columns) + 1));
  const row = Math.max(1, Math.min(rows, Math.floor(((bounds.maxY - y) / (bounds.maxY - bounds.minY)) * rows) + 1));
  return { column, row };
}

function polygonBounds(rings) {
  const points = rings.flat();
  return {
    minLon: Math.min(...points.map(([lon]) => lon)),
    maxLon: Math.max(...points.map(([lon]) => lon)),
    minLat: Math.min(...points.map(([, lat]) => lat)),
    maxLat: Math.max(...points.map(([, lat]) => lat)),
  };
}

function pointInRing(point, ring) {
  const [lon, lat] = point;
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    const intersects = yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi || Number.EPSILON) + xi;
    if (intersects) inside = !inside;
  }
  return inside;
}

function pointInPolygon(point, rings) {
  if (!pointInRing(point, rings[0])) return false;
  return !rings.slice(1).some((hole) => pointInRing(point, hole));
}

function geometryPolygons(geometry) {
  if (geometry.type === 'Polygon') return [geometry.coordinates];
  if (geometry.type === 'MultiPolygon') return geometry.coordinates;
  return [];
}

async function loadLandGeoJson() {
  const response = await fetch(landUrl);
  if (!response.ok) throw new Error(`Could not fetch Natural Earth land data: ${response.status}`);
  return response.json();
}

function markCell(cells, bounds, lon, lat) {
  if (lat < latitudeExtent.min || lat > latitudeExtent.max) return;
  const { column, row } = coordinateToCell(lon, lat, bounds);
  cells.add(`${column}:${row}`);
}

function rasterizeLandCells(geojson, bounds) {
  const cells = new Set();
  for (const feature of geojson.features ?? []) {
    for (const rings of geometryPolygons(feature.geometry)) {
      const bbox = polygonBounds(rings);
      for (let lon = Math.floor(bbox.minLon); lon <= Math.ceil(bbox.maxLon); lon += sampleStepDegrees) {
        const minLat = Math.max(latitudeExtent.min, Math.floor(bbox.minLat));
        const maxLat = Math.min(latitudeExtent.max, Math.ceil(bbox.maxLat));
        for (let lat = minLat; lat <= maxLat; lat += sampleStepDegrees) {
          if (pointInPolygon([lon, lat], rings)) markCell(cells, bounds, lon, lat);
        }
      }
      for (const ring of rings) {
        for (const [lon, lat] of ring) markCell(cells, bounds, lon, lat);
      }
    }
  }
  return Array.from(cells).sort((a, b) => {
    const [ac, ar] = a.split(':').map(Number);
    const [bc, br] = b.split(':').map(Number);
    return ar - br || ac - bc;
  });
}

function renderModule(bounds, landCells) {
  const projectedRatio = (bounds.maxX - bounds.minX) / (bounds.maxY - bounds.minY);
  const gridRatio = columns / rows;
  return `// Generated by pipeline/generate_world_pixel_atlas.mjs. Do not edit by hand.
export interface WorldPixelCell {
  column: number;
  row: number;
}

export const worldPixelAtlas = {
  columns: ${columns},
  rows: ${rows},
  projection: 'equal-earth',
  latitudeExtent: ${JSON.stringify(latitudeExtent)},
  projectedRatio: ${Number(projectedRatio.toFixed(6))},
  gridRatio: ${Number(gridRatio.toFixed(6))},
  ratioError: ${Number(Math.abs(projectedRatio - gridRatio).toFixed(6))},
  source: '${landUrl}',
  bounds: ${JSON.stringify(bounds)},
  landCells: ${JSON.stringify(landCells)},
} as const;

const landCellSet = new Set<string>(worldPixelAtlas.landCells);

export function worldPixelKey(column: number, row: number) {
  return String(column) + ':' + String(row);
}

export function isWorldPixelLand(column: number, row: number) {
  return landCellSet.has(worldPixelKey(column, row));
}

export function projectLonLatToWorldCell(lon: number, lat: number): WorldPixelCell {
  const lambda = (lon * Math.PI) / 180;
  const phi = (lat * Math.PI) / 180;
  const theta = Math.asin((Math.sqrt(3) / 2) * Math.sin(phi));
  const theta2 = theta * theta;
  const theta6 = theta2 * theta2 * theta2;
  const a1 = 1.340264;
  const a2 = -0.081106;
  const a3 = 0.000893;
  const a4 = 0.003796;
  const denominator = 3 * (9 * a4 * theta6 * theta2 + 7 * a3 * theta6 + 3 * a2 * theta2 + a1);
  const x = (2 * Math.sqrt(3) * lambda * Math.cos(theta)) / denominator;
  const y = a4 * theta6 * theta2 * theta + a3 * theta6 * theta + a2 * theta2 * theta + a1 * theta;
  const bounds = worldPixelAtlas.bounds;
  return {
    column: Math.max(1, Math.min(worldPixelAtlas.columns, Math.floor(((x - bounds.minX) / (bounds.maxX - bounds.minX)) * worldPixelAtlas.columns) + 1)),
    row: Math.max(1, Math.min(worldPixelAtlas.rows, Math.floor(((bounds.maxY - y) / (bounds.maxY - bounds.minY)) * worldPixelAtlas.rows) + 1)),
  };
}
`;
}

const bounds = computeBounds();
const geojson = await loadLandGeoJson();
const landCells = rasterizeLandCells(geojson, bounds);
await fs.writeFile(outPath, renderModule(bounds, landCells));
console.log(`Generated ${landCells.length} land cells at ${path.relative(process.cwd(), outPath)}.`);
